### ISSUE TITLE
Why did you remove Consolas?

### ISSUE THREAD

**Issue by denvercoder** [nicolashery/mac-dev-setup#51]
I see that you removed CONSOLAS from the 2.0 version. I know that it doesn't work but I got it to work by just running open CONSOLA*.TTF twice. I hit enter, then Import Font, then immediately go back the the terminal and hit the up arrow and do it again. The second time I get a message saying there were minor issues but it still all works.

Just wondering.

**Comment by nicolashery** [comment]
Thanks for the explanation. I didn't know about this issue.

The main reason I removed Consolas from the guide, is that I realized that I personally never really settled on a particular font (I'm currently using [Iosevka](https://typeof.net/Iosevka/) if you're curious). Since this is a beginner's guide, I consider the default fonts to be good enough to get started.
