### ISSUE TITLE
This project seems not maintain.

### ISSUE THREAD

**Issue by Svtter** [nicolashery/mac-dev-setup#61]
Lots of items has been overdue.

**Comment by denvercoder** [comment]
I’m not really a maintainer but I have been using this repo for over 2 years. Is there something I can help with. Also, there is a 2.0 branch with some new stuff.

**Comment by aakent** [comment]
@denvercoder Any other recommended step-by-step guides like this?  Has 2.0 branch been verified recently as up to date?

**Comment by nicolashery** [comment]
Sorry it took a while, I only review the whole guide when I set up a new machine. It turns out I don't do that very often. But I did recently, and pushed a new version of the guide (https://github.com/nicolashery/mac-dev-setup/commit/bffbe4b741052d6122a6f690d9fb2b5172130a2a). That should bring everything up-to-date.

**Comment by Svtter** [comment]
Thinks for your work. Just want to remind newbie.
